name: e_commerce_clothing_store_mobile_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^3.13.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  cupertino_icons: ^1.0.6
  
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/cash.png
    - lib/assets/credit.png
    - lib/assets/paypal.png
    - lib/assets/images/watch.png
    - lib/assets/images/earpod.png
    - lib/assets/images/hoodie.png
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins-Medium.ttf
          weight: 500
  
