name: e_commerce_clothing_store_mobile_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.3.0
  firebase_core: ^3.13.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  cupertino_icons: ^1.0.6

  user_repository:
    path: packages/user_repository
  flutter_svg: ^2.0.17
  go_router: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/airpods.png
    - lib/assets/hoodie.png
    - lib/assets/watch.png
    - lib/assets/black_white_nike.png
    - lib/assets/jacket.png
    - lib/assets/TV.png
    - lib/assets/white_t_shirt.png
    - lib/assets/t-shirt_girl.png
    - lib/assets/profile_picture.png
    -  lib/assets/child_cloth.png
    - lib/assets/icons/bars.svg
    - lib/assets/icons/wifi.svg
    - lib/assets/icons/battery_full.svg
    - lib/assets/icons/bell.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins-Medium.ttf
          weight: 500
